<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>YoneDesktopPet</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\yone.jpg" Condition="Exists('Assets\yone.jpg')" />
    <Resource Include="Assets\向左飞行.png" Condition="Exists('Assets\向左飞行.png')" />
  </ItemGroup>

</Project>
